---

- alias: Send matt a sms when nobody is home
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    service: notify.send_matt
    data:
      message: 'everyone has left the house'
      target:
        - !env_var MATT_SMS_EMAIL

- alias: Send matt a sms when somebody gets home
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  action:
    service: notify.send_matt
    data:
      message: 'somebody is now home'
      target:
        - !env_var MATT_SMS_EMAIL

- alias: Send matt a sms when file starts downloading
  trigger:
    platform: state
    entity_id: sensor.sab_status
    from: 'Idle'
    to: 'Downloading'
  action:
    service: notify.send_matt
    data:
      message: 'file downloading'
      target:
        - !env_var MATT_SMS_EMAIL

- alias: Update notifications
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    service: notify.send_matt
    data:
      message: 'There is a new Home Assistant release available.'
      target:
        - !env_var MATT_SMS_EMAIL
