---

homeassistant: !include homeassistant.yaml

weblink: !include weblinks.yaml

notify: !include notify.yaml

zone: !include_dir_merge_list zones

proximity: !include proximity.yaml

media_player: !include media_player.yaml

device_tracker: !include device_tracker.yaml

sensor: !include sensors.yaml

nest:
  client_id: !env_var NEST_CLIENT_ID
  client_secret: !env_var NEST_SECRET

climate:
  platform: nest

group: !include groups.yaml

digital_ocean:
  access_token: !env_var DIGITAL_OCEAN_KEY

binary_sensor: !include binary_sensor.yaml

# Discover some devices automatically
discovery:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Allows you to issue voice commands from the frontend
conversation:

# Checks for available updates
updater:

# Enables the frontend
frontend:

# Enables support for tracking state changes over time.
history:

http:
  api_password: !env_var HTTP_API_PASSWORD

mqtt: !include mqtt.yaml

automation: !include_dir_merge_list automation

vera:
  vera_controller_url: !env_var VERA_URL 
  lights: [5, 6, 8]

tts:
  - platform: google

influxdb:
  host: !env_var INFLUXDB_HOST
  database: !env_var INFLUXDB_DATABASE
  username: !env_var INFLUXDB_USERNAME
  password: !env_var INFLUXDB_PASSWORD
  default_measurement: state
  tags:
    instance: prod
    source: hass
