---

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: cpuspeed
  name: CPU

- platform: darksky
  api_key: !env_var FORECAST_API_KEY
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility

- platform: sabnzbd
  name: SAB
  api_key: !env_var SAB_API_KEY
  host: !env_var SAB_HOST
  port: !env_var SAB_PORT
  monitored_variables:
    - 'current_status'
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_size'
    - 'disk_free'

- platform: gtfs
  data: uta.zip 
  origin: 18382
  destination: 18384
