---

- alias: Open front door automation
  trigger:
    platform: state
    entity_id: binary_sensor.front_door_sensor_10
    from: 'off'
    to: 'on'
  action:
    - service: notify.send_matt
      data:
        message: 'Front Door Open'
        target:
          - !env_var MATT_SMS_EMAIL
    - service: tts.google_say
      data:
        message: 'Front Door Open'
