---

- alias: Open garage automation
  trigger:
    platform: state
    entity_id: cover.garage_door_opener
    from: 'closed'
    to: 'open'
  action:
    - service: notify.send_matt
      data:
        message: 'Garage Open'
        target:
          - !env_var MATT_SMS_EMAIL
    - service: tts.google_say
      entity_id: group.google_home
      data:
        message: 'Garage Open'
