---

- alias: Nobody home 
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: notify.send_matt
      data:
        message: 'everyone has left the house'
        target:
          - !env_var MATT_SMS_EMAIL
